### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by NotDarkn** [Whelement/Tr3nch#3]
lots of backlash :O

https://github.com/Whelement/Tr3nch/assets/73033672/55454593-b8dc-4d04-8a81-ee79b2935b9e

so what's gonna happen to tr3nch

**Comment by NotDarkn** [comment]
c'mon i just wanna know

**Comment by MunyDev** [comment]
why even hate on Tr3nch. Honestly it is the only recent activity in chrome os anyways. Soon Tr3nch will be useful, with a surprise coming after APUSH testing....

**Comment by NotDarkn** [comment]
> why even hate on Tr3nch. Honestly it is the only recent activity in chrome os anyways. Soon Tr3nch will be useful, with a surprise coming after testing

i wasn't hating on Tr3nch in this issue i was genuinely asking what's gonna happen to it

**Comment by ZeglolTheThirtySixth** [comment]
Nothing is going to happen to it, it's going to be updated as time goes on as promised

**Comment by NotDarkn** [comment]
> Nothing is going to happen to it, it's going to be updated as time goes on as promised

oki
