### ISSUE TITLE
TL:DR: Tr3nch is basically patched unless you already were able to have skiovox breakout.

### ISSUE THREAD

**Issue by alexstilldraws** [Whelement/Tr3nch#7]
(hear me out on this)

Due to writable leaving the unblocking community, he deleted skiovox breakout, which means unless you already had skiovox breakout, you can't use Tr3nch. 
Even if you **DID** have it, you still have to worry about policy blocks, which cooks you because only one ID can be used for skiovox breakout. Therefore, unless somehow skiovox breakout is fixed or your school lets you use it, tr3nch is unusable.

**Comment by TheSpiritOfDark** [comment]
Tr3nch doesn't require skiovox breakout, it works with any ace in an extension with the correct perms, we used skiovox breakout as an example because it's universal.

**Comment by alexstilldraws** [comment]
wdym by universal? i thought only one id had those perms?

**Comment by TheSpiritOfDark** [comment]
I meant that skiovox breakout can inject tr3nch into any extension, assuming it's not patched for you, so you don't need ace in a specific extension to run tr3nch
